version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm run-script build &&
      - aws cloudfront create-invalidation --distribution-id=E17A4U8JG69Z4B --paths '/*'
artifacts:
  files:
    - ./*
  name: angular-build
  discard-paths: no
  base-directory: dist/SoftEng-API-Site

